// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqcfkcgsfursefhdczyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxY2ZrY2dzZnVyc2VmaGRjenlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDk3OTAsImV4cCI6MjA3MDEyNTc5MH0.5K6E1cwnIKV9bzfA46FQOpe3N7glQ_lKtp8Obqcs9oU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});