// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byaqdyqqwmkgeypvmxgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5YXFkeXFxd21rZ2V5cHZteGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTU5NDcsImV4cCI6MjA3MjY3MTk0N30.NkDeX3b6NwXYok5VtYIJkPI9z98WcdIQARw8HyZChxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});